work_dir: ./work_dir/NTU-RGB-D/xsub/ST_GCN

# feeder
feeder: st_gcn.feeder.Feeder
train_feeder_args:
  data_path: ./data/NTU-RGB-D/xsub/train_data.npy
  label_path: ./data/NTU-RGB-D/xsub/train_label.pkl
test_feeder_args:
  data_path: ./data/NTU-RGB-D/xsub/val_data.npy
  label_path: ./data/NTU-RGB-D/xsub/val_label.pkl

# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 60
  channel: 3
  window_size: 300
  num_point: 25
  num_person: 2
  graph: st_gcn.graph.NTU_RGB_D
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True 

# training
base_lr: 0.035
batch_size: 22
# device: [0,1,2,3]
device: [0]
eval_interval: 80
global_step: 0
nesterov: True
num_epoch: 80
num_worker: 8
save_interval: 1
start_epoch: 0
step: [10, 50]
#step: [10, 20]
test_batch_size: 16
weight_decay: 0.0001



