work_dir: ./work_dir/Kinetics/TCN

# feeder
feeder: st_gcn.feeder.Feeder
train_feeder_args:
  random_move: True
  data_path: ./data/Kinetics/kinetics-skeleton/train_data.npy
  label_path: ./data/Kinetics/kinetics-skeleton/train_label.pkl
test_feeder_args:
  data_path: ./data/Kinetics/kinetics-skeleton/val_data.npy
  label_path: ./data/Kinetics/kinetics-skeleton/val_label.pkl

# model
model: st_gcn.net.TCN
model_args:
  num_class: 400
  channel: 108 
  window_size: 300
  use_data_bn: True

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 60]

# training
device: [0,1,2,3]  
batch_size: 512 
test_batch_size: 512 
num_epoch: 60
nesterov: True


